name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: danieldbr/flask-webserver:latest

  Deploy:
      runs-on: ubuntu-latest
      needs: Build
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Nomad CLI
        uses: hashicorp/setup-nomad@main
  
      - name: Deploy to Nomad
        env:
          NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
        run: nomad run flask-webserver.nomad
